# Generated by Django 5.1.2 on 2024-10-21 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("TB2", "Tb2"),
                            ("TB3", "Tb3"),
                            ("AKINCI", "Akinci"),
                            ("KIZILELMA", "Kizilelma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AircraftPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Wing", "Wing"),
                            ("Fuselage", "Fuselage"),
                            ("Tail", "Tail"),
                            ("Avionics", "Avionics"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("TB2", "Tb2"),
                            ("TB3", "Tb3"),
                            ("AKINCI", "Akinci"),
                            ("KIZILELMA", "Kizilelma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aircrafts.aircraft",
                    ),
                ),
            ],
        ),
    ]
